# Generated by Django 2.2.23 on 2021-06-01 01:21

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ids', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('idt', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=10)),
                ('price', models.IntegerField(default=45)),
                ('field', models.FileField(upload_to='')),
                ('image', models.ImageField(null=True, upload_to='images', verbose_name='')),
                ('phone', models.IntegerField(default=0)),
                ('is_ok', models.BooleanField(default=False)),
                ('courses', models.CharField(default='', max_length=100)),
                ('rate', models.IntegerField(default=0)),
                ('coursees', models.ManyToManyField(to='app.course')),
            ],
            options={
                'db_table': 'tutors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shop', models.DateField(default=datetime.datetime.now)),
                ('numlessons', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
        ),
    ]
