# Generated by Django 2.2.23 on 2021-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email0',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
