# Generated by Django 2.2.20 on 2021-05-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
