# Generated by Django 2.2.19 on 2021-04-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210405_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='price',
            field=models.IntegerField(default=45),
        ),
    ]
