# Generated by Django 2.2.23 on 2021-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tutor_email0'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('content', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.AddField(
            model_name='tutor',
            name='messages',
            field=models.ManyToManyField(to='app.message'),
        ),
    ]
