# Generated by Django 2.2.22 on 2021-06-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210601_1254'),
        ('app', '0002_student_color'),
    ]

    operations = [
    ]
