# Generated by Django 2.2.19 on 2021-04-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210405_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
