# Generated by Django 2.2.20 on 2021-04-06 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210405_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='username',
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=11, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(to='app.tutor'),
        ),
    ]
