# Generated by Django 2.2.23 on 2021-06-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210603_0526'),
        ('app', '0005_auto_20210603_0327'),
    ]

    operations = [
    ]
