# Generated by Django 2.2.20 on 2021-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210406_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
