# Generated by Django 2.2.24 on 2021-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210603_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='changeview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'changeview',
            },
        ),
    ]
