# Generated by Django 2.2.24 on 2021-06-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_changeview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeview',
            name='color',
            field=models.CharField(default='blue', max_length=1000),
        ),
    ]
