# Generated by Django 2.2.20 on 2021-04-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tutor_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
        migrations.AlterModelTable(
            name='tutor',
            table='totur',
        ),
    ]
