# Generated by Django 2.2.20 on 2021-04-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210411_1238'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tutor',
            table='tutors',
        ),
    ]
