# Generated by Django 2.2.20 on 2021-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210411_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(to='app.tutor'),
        ),
    ]
