# Generated by Django 2.2.20 on 2021-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210422_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tutors',
        ),
        migrations.AddField(
            model_name='tutor',
            name='coursees',
            field=models.ManyToManyField(to='app.course'),
        ),
    ]
