# Generated by Django 2.2.20 on 2021-04-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210422_1026'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
