# Generated by Django 2.2.20 on 2021-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_student_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/', verbose_name=''),
        ),
    ]
