# Generated by Django 2.2.20 on 2021-05-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_student_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
